In [2]:
import numpy as np

In [ ]:
## 0-D Arrays/ Scalar
arr = np.array(42)
print(arr)

42


In [ ]:
## 1-D Arrays
my_one_dim = np.array([1,2,3])
print(my_one_dim)

[1 2 3]


In [ ]:
## 2D Arrays
my_two_dim = np.array([[1,2,3], [4, 5, 6]])
print(my_two_dim)

[[1 2 3]
 [4 5 6]]


In [ ]:
## 3 D Arrays
my_three_dim = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(my_three_dim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
## initializing a numpy array
number_of_rows = 3
number_of_columns = 2
arrays_of_zero = np.ones((number_of_rows, number_of_columns))

In [ ]:
print(arrays_of_zero)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arrays_of_5s = 6 * np.full((number_of_rows, number_of_columns), 6)
print(arrays_of_5s)

[[36 36]
 [36 36]
 [36 36]]


In [ ]:
#10-25 -- interval 10, 13, 16 ------ 22
start = 10
end = 28
step = 3
evenly_step = np.arange(start, end, step)
evenly_step

array([10, 13, 16, 19, 22, 25])

In [ ]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
random01 = np.random.random((2,3))
print(random01)

[[0.7838877  0.03144343 0.99635002]
 [0.34493054 0.4821017  0.88504203]]


In [ ]:
randomintrange = np.random.randint(0, 10, (2,3))
print(randomintrange)

[[5 0 9]
 [7 4 4]]


In [ ]:
## numpy array and a python list behaves similarly
list = [1,2,3]
arr = np.array([1,2,3])

In [ ]:
a = np.array([[5,6,3], [2,5,1]])
a.ndim ## dimension
a.shape ##shape
a.size ##size
a.dtype ##data type

dtype('int32')

In [4]:
## array
arr1 = np.array([0,2,4,5,3,7,8,9,5,1])
## odd numbers are numbers that when that gives a remainder when divided
arr1[arr1 % 2 ==1] = -1*arr1[arr1 % 2 ==1]

In [5]:
print(arr1)

[ 0  2  4 -5 -3 -7  8 -9 -5 -1]


In [ ]:
## numpy array arithmetics
a = np.array([[1,2,5], [7,1,3]])
b = np.array([[4,6,9], [2,5,1]])

In [ ]:
add1= a + b 
print(add1)

[[ 5  8 14]
 [ 9  6  4]]


In [ ]:
add2 = np.add(a,b)
print(add2)

[[ 5  8 14]
 [ 9  6  4]]


In [ ]:
## subtraction of array
sub1 = a - b
print(sub1)

[[-3 -4 -4]
 [ 5 -4  2]]


In [ ]:
sub2 = np.subtract(a,b)
print(sub2)

[[-3 -4 -4]
 [ 5 -4  2]]


In [ ]:
## multiply
mul1 = a * b 
print(mul1)

[[ 4 12 45]
 [14  5  3]]


In [ ]:
mul2 = np.multiply(a,b)
print(mul2)

[[ 4 12 45]
 [14  5  3]]


In [ ]:
## division
div1 = a / b
print(div1)

[[0.25       0.33333333 0.55555556]
 [3.5        0.2        3.        ]]


In [ ]:
div2 = np.divide(a,b)
print(div2)

[[0.25       0.33333333 0.55555556]
 [3.5        0.2        3.        ]]


In [ ]:
##exponential
##square root
## sin 
## cos
##log


In [ ]:
maxi = a.max()
print(maxi)

7


In [ ]:
minimum = a.min()
print(minimum)

1


In [ ]:
standard_dev = np.std(a)
print(standard_dev)

2.1921577396609844


In [ ]:
abc = np.hstack([a,b])
print(a,b)

[[1 2 5]
 [7 1 3]] [[4 6 9]
 [2 5 1]]
